TYPE = exe
SOURCES = test.cpp
INCLUDES = -I. -I/usr/local/include -I../src
LIBS = ../libRegExp.a -lpcre
OUT = test

#-----------------------------------------------------------------
include ../build.mk

