TYPE = exe
SOURCES = test.cpp
INCLUDES = -I. -I/usr/local/include -I$(PWD)/../src
LIBS = ../libRegExp.a
INSLIBS = -lpcre
OUT = test

#-----------------------------------------------------------------
include ../build.mk

